addons:
  mariadb: '10.1'
language: java
dist: trusty
jdk:
  - openjdk8
before_install:
  - wget http://services.gradle.org/distributions/gradle-5.4-bin.zip
  - unzip -qq gradle-5.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
script:
  - mysql --user="root" --execute="DROP SCHEMA IF EXISTS demo; CREATE SCHEMA demo;"
  - mysql -u root demo < src/main/resources/migration/V1.1__create_employee_table.sql
  - mysql -u root demo < src/main/resources/migration/V1.2__seed_employees.sql
  - gradle clean build test
after_success:
  - chmod +x ./src/main/resources/util_script/pr_comment.sh
  - ./src/main/resources/util_script/pr_comment.sh
before_cache:
  - sudo chown -R travis:travis $HOME/.gradle/caches/modules-2
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email:
    - arindam.nayak@outlook.com