language: java
dist: trusty
jdk:
  - openjdk8
script:
  - gradle clean build test
before_cache:
  - sudo chown -R travis:travis $HOME/.gradle/caches/modules-2
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email:
    - arindam.nayak@outlook.com